import { useEffect, useState } from 'react';
import { useGetIdentity, useLogout } from '@refinedev/core';
import { Bell, Check, CircleUserRound, LogOut, Mail, Save, ShieldCheck } from 'lucide-react';

type Identity = { id: string; name?: string; email?: string; role?: string; avatar?: string };
type Preferences = { scheduleReminder: boolean; progressReminder: boolean; autoplay: boolean };
const defaults: Preferences = { scheduleReminder: true, progressReminder: false, autoplay: false };

export function ProfilePage() {
  const { data: identity } = useGetIdentity<Identity>();
  const { mutate: logout, isPending: isLoggingOut } = useLogout();
  const storageKey = `uah_participant_preferences_${identity?.id || 'demo-peserta-1'}`;
  const [preferences, setPreferences] = useState<Preferences>(defaults);
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { setPreferences(JSON.parse(localStorage.getItem(storageKey) || 'null') || defaults); } catch { setPreferences(defaults); } }, [storageKey]);
  const save = () => { localStorage.setItem(storageKey, JSON.stringify(preferences)); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  const options: Array<{ key: keyof Preferences; label: string; helper: string }> = [
    { key: 'scheduleReminder', label: 'Pengingat jadwal kajian', helper: 'Tandai preferensi untuk pembaruan agenda dan perubahan jadwal.' },
    { key: 'progressReminder', label: 'Pengingat melanjutkan belajar', helper: 'Ingatkan ketika masih ada pertemuan yang belum selesai.' },
    { key: 'autoplay', label: 'Putar materi berikutnya otomatis', helper: 'Siapkan pertemuan selanjutnya setelah materi ditandai selesai.' },
  ];

  return <div className="space-y-6"><header><h1 className="break-words text-2xl font-bold tracking-tight text-slate-950">Profil & Preferensi</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Periksa identitas akun dan atur pengalaman belajar pada perangkat ini.</p></header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,.7fr)_minmax(0,1.3fr)]"><section className="rounded-2xl border border-stone-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-4"><img src={identity?.avatar || '/logo-abu-haidar.jpg'} alt="Foto profil" className="h-16 w-16 rounded-xl border border-stone-200 object-cover" /><div className="min-w-0"><h2 className="truncate text-lg font-bold text-slate-950">{identity?.name || 'Peserta Kajian'}</h2><p className="mt-1 inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-800"><ShieldCheck className="h-3.5 w-3.5" /> Akun peserta</p></div></div><dl className="mt-6 space-y-4 border-t border-stone-200 pt-5"><div><dt className="text-[11px] font-bold uppercase tracking-wide text-slate-400">Nama</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{identity?.name || 'Belum tersedia'}</dd></div><div><dt className="text-[11px] font-bold uppercase tracking-wide text-slate-400">Email</dt><dd className="mt-1 flex min-w-0 items-center gap-2 text-sm text-slate-700"><Mail className="h-4 w-4 shrink-0 text-slate-400" /><span className="truncate">{identity?.email || 'Belum tersedia'}</span></dd></div><div><dt className="text-[11px] font-bold uppercase tracking-wide text-slate-400">ID akun</dt><dd className="mt-1 break-all font-mono text-xs text-slate-500">{identity?.id || '—'}</dd></div></dl><p className="mt-5 rounded-lg bg-stone-100 px-3 py-3 text-xs leading-5 text-slate-500">Perubahan nama atau email mengikuti penyedia akun yang digunakan saat masuk.</p></section>
      <section className="rounded-2xl border border-stone-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-50 text-emerald-800"><Bell className="h-5 w-5" /></span><div><h2 className="text-base font-bold text-slate-950">Preferensi belajar</h2><p className="mt-1 text-xs text-slate-500">Disimpan secara privat di browser ini.</p></div></div><div className="mt-5 divide-y divide-stone-200">{options.map((option) => <label key={option.key} className="flex cursor-pointer items-start justify-between gap-4 py-4 first:pt-0"><span><span className="block text-sm font-bold text-slate-800">{option.label}</span><span className="mt-1 block max-w-xl text-xs leading-5 text-slate-500">{option.helper}</span></span><input type="checkbox" checked={preferences[option.key]} onChange={(event) => setPreferences((current) => ({ ...current, [option.key]: event.target.checked }))} className="mt-1 h-5 w-5 shrink-0 accent-emerald-700" /></label>)}</div><div className="mt-5 flex flex-col gap-2 border-t border-stone-200 pt-5 sm:flex-row sm:items-center sm:justify-between"><span role="status" className={`inline-flex min-h-10 items-center gap-2 text-xs font-semibold text-emerald-800 ${saved ? 'visible' : 'invisible'}`}><Check className="h-4 w-4" /> Preferensi tersimpan</span><button type="button" onClick={save} className="inline-flex min-h-11 items-center justify-center gap-2 whitespace-nowrap rounded-lg bg-emerald-700 px-4 text-sm font-bold text-white hover:bg-emerald-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-700 active:bg-emerald-900"><Save className="h-4 w-4" /> Simpan preferensi</button></div></section></div>
    <section className="flex flex-col gap-4 rounded-2xl border border-rose-200 bg-rose-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><CircleUserRound className="mt-0.5 h-5 w-5 shrink-0 text-rose-700" /><div><h2 className="text-sm font-bold text-rose-900">Sesi akun</h2><p className="mt-1 text-xs leading-5 text-rose-700">Keluar dari portal pada perangkat ini. Catatan lokal tetap tersimpan di browser.</p></div></div><button type="button" onClick={() => logout()} disabled={isLoggingOut} className="inline-flex min-h-11 items-center justify-center gap-2 whitespace-nowrap rounded-lg border border-rose-300 bg-white px-4 text-sm font-bold text-rose-800 hover:bg-rose-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-700 disabled:cursor-not-allowed disabled:opacity-55"><LogOut className="h-4 w-4" /> {isLoggingOut ? 'Keluar…' : 'Keluar dari akun'}</button></section>
  </div>;
}
