import { useEffect, useMemo, useState } from 'react';
import { useGetIdentity } from '@refinedev/core';
import { Link } from 'react-router-dom';
import { CheckCircle2, Circle, Clock3, Play, TrendingUp } from 'lucide-react';
import { getProgramProgress, getUserEnrollments, getUserLessonProgress } from '@/lib/userStore';
import { getLessonsForProgram, useParticipantPortalData } from './useParticipantPortalData';

export function ProgressPage() {
  const { data: identity } = useGetIdentity<{ id: string }>();
  const userId = identity?.id || 'demo-peserta-1';
  const { programs, lessons } = useParticipantPortalData();
  const [progress, setProgress] = useState(() => getUserLessonProgress(userId));
  const [filter, setFilter] = useState<'all' | 'active' | 'done'>('all');
  useEffect(() => setProgress(getUserLessonProgress(userId)), [userId]);
  const enrolledIds = useMemo(() => new Set(getUserEnrollments(userId).filter((item) => item.status === 'active').map((item) => item.programId)), [userId]);
  const relevantPrograms = programs.filter((program) => enrolledIds.has(program.id) || lessons.some((lesson) => lesson.programId === program.id && progress.some((item) => item.lessonId === lesson.id)));
  const relevantLessons = lessons.filter((lesson) => relevantPrograms.some((program) => program.id === lesson.programId));
  const completed = relevantLessons.filter((lesson) => progress.some((item) => item.lessonId === lesson.id && item.isCompleted));
  const active = relevantLessons.filter((lesson) => progress.some((item) => item.lessonId === lesson.id && !item.isCompleted && item.lastPositionSeconds > 0));
  const percentage = relevantLessons.length ? Math.round((completed.length / relevantLessons.length) * 100) : 0;
  const activity = [...progress].sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt)).filter((item) => {
    if (filter === 'done') return item.isCompleted;
    if (filter === 'active') return !item.isCompleted;
    return true;
  });

  return <div className="space-y-6"><header><h1 className="break-words text-2xl font-bold tracking-tight text-slate-950">Progres Belajar</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Lihat capaian lintas program dan lanjutkan materi yang belum selesai.</p></header>
    <section className="grid gap-4 rounded-2xl border border-stone-200 bg-white p-5 sm:grid-cols-[12rem_minmax(0,1fr)] sm:items-center sm:p-6"><div className="mx-auto flex h-36 w-36 items-center justify-center rounded-full bg-[conic-gradient(var(--color-accent)_var(--progress),var(--color-paper-2)_0)] p-3" style={{ '--progress': `${percentage * 3.6}deg` } as React.CSSProperties}><div className="flex h-full w-full flex-col items-center justify-center rounded-full bg-white"><span className="text-3xl font-bold text-slate-950">{percentage}%</span><span className="mt-1 text-[11px] font-semibold text-slate-500">keseluruhan</span></div></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-800">Capaian Anda</p><h2 className="mt-2 text-xl font-bold text-slate-950">{completed.length} pertemuan telah selesai</h2><p className="mt-2 text-sm leading-6 text-slate-600">{active.length > 0 ? `${active.length} pertemuan sedang dipelajari dan dapat dilanjutkan.` : 'Belum ada materi yang sedang berjalan.'}</p><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-lg bg-stone-100 p-3"><p className="text-lg font-bold">{relevantPrograms.length}</p><p className="text-[11px] text-slate-500">Program</p></div><div className="rounded-lg bg-stone-100 p-3"><p className="text-lg font-bold">{active.length}</p><p className="text-[11px] text-slate-500">Berjalan</p></div><div className="rounded-lg bg-stone-100 p-3"><p className="text-lg font-bold">{completed.length}</p><p className="text-[11px] text-slate-500">Selesai</p></div></div></div></section>
    <section className="grid gap-4 xl:grid-cols-2">{relevantPrograms.map((program) => { const programLessons = getLessonsForProgram(lessons, program.id); const info = getProgramProgress(userId, programLessons); return <article key={program.id} className="rounded-xl border border-stone-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-bold text-slate-950">{program.title}</h2><p className="mt-1 text-xs text-slate-500">{info.completedCount} dari {info.totalCount} pertemuan</p></div><span className="text-sm font-bold text-emerald-800">{info.percentage}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-emerald-700" style={{ width: `${info.percentage}%` }} /></div><div className="mt-4 flex max-h-48 flex-col gap-1 overflow-y-auto">{programLessons.map((lesson) => { const item = progress.find((entry) => entry.lessonId === lesson.id); return <Link key={lesson.id} to={`/lesson/${lesson.id}`} className="flex min-h-11 items-center gap-3 rounded-lg px-2 text-xs text-slate-600 hover:bg-stone-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-700">{item?.isCompleted ? <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-700" /> : item?.lastPositionSeconds ? <Play className="h-4 w-4 shrink-0 text-amber-600" /> : <Circle className="h-4 w-4 shrink-0 text-stone-300" />}<span className="min-w-0 flex-1 truncate">{lesson.sequence}. {lesson.title}</span>{item?.lastPositionSeconds ? <span className="shrink-0 text-[10px] text-slate-400">{Math.floor(item.lastPositionSeconds / 60)}m</span> : null}</Link>; })}</div></article>; })}{relevantPrograms.length === 0 && <div className="rounded-xl border border-dashed border-stone-300 bg-white px-5 py-10 text-center xl:col-span-2"><TrendingUp className="mx-auto h-7 w-7 text-slate-400" /><p className="mt-3 text-sm font-bold text-slate-800">Belum ada progres yang tercatat</p><Link to="/belajar" className="mt-3 inline-flex min-h-10 items-center text-xs font-bold text-emerald-800">Pilih kajian untuk mulai</Link></div>}</section>
    <section className="rounded-2xl border border-stone-200 bg-white p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-slate-950">Aktivitas terakhir</h2><p className="mt-1 text-xs text-slate-500">Riwayat posisi dan penyelesaian materi di perangkat ini.</p></div><div className="grid grid-cols-3 gap-1 rounded-lg bg-stone-100 p-1">{([['all','Semua'],['active','Berjalan'],['done','Selesai']] as const).map(([value,label]) => <button key={value} type="button" onClick={() => setFilter(value)} className={`min-h-10 whitespace-nowrap rounded-md px-3 text-xs font-bold ${filter === value ? 'bg-white text-emerald-900 shadow-xs' : 'text-slate-500 hover:text-slate-900'}`}>{label}</button>)}</div></div><div className="mt-5 divide-y divide-stone-200">{activity.map((item) => { const lesson = lessons.find((entry) => entry.id === item.lessonId); if (!lesson) return null; return <div key={item.id} className="flex flex-col gap-3 py-4 first:pt-0 sm:flex-row sm:items-center"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${item.isCompleted ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{item.isCompleted ? <CheckCircle2 className="h-4 w-4" /> : <Clock3 className="h-4 w-4" />}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-900">{lesson.title}</p><p className="mt-1 text-xs text-slate-500">{item.isCompleted ? 'Ditandai selesai' : `Terakhir di menit ${Math.floor(item.lastPositionSeconds / 60)}`} · {new Date(item.updatedAt).toLocaleDateString('id-ID')}</p></div><Link to={`/lesson/${lesson.id}`} className="inline-flex min-h-10 items-center justify-center whitespace-nowrap rounded-lg border border-stone-300 px-3 text-xs font-bold text-slate-700 hover:bg-stone-100">Buka materi</Link></div>; })}{activity.length === 0 && <p className="py-8 text-center text-sm text-slate-500">Belum ada aktivitas untuk filter ini.</p>}</div></section>
  </div>;
}
