/* Hallmark · pre-emit critique: P5 H5 E5 S5 R5 V5
 * Hallmark · genre: modern-minimal · macrostructure: expandable curriculum workbench · design-system: design.md · designed-as-app
 */
import { useMemo, useState } from 'react';
import { useCreate, useDelete, useList, useOne, useUpdate } from '@refinedev/core';
import { BookOpenCheck, ChevronDown, Edit3, FileAudio, FileQuestion, Files, FileText, Link2, LoaderCircle, Plus, Trash2, Video, X } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { MaterialViewer } from '../../components/material/MaterialViewer';
import { AdminLessonForm } from './AdminLessonForm';
import { AdminMaterialDialog, type LessonMaterial } from './AdminMaterialDialog';
import { AdminQuizDialog, type LessonQuiz } from './AdminQuizDialog';

interface ChapterItem { id: string; title: string; sequence: number }
interface CurriculumLessonItem { id: string; chapterId?: string; title: string; sequence: number; status: 'draft' | 'published'; materialCount?: number; hasQuiz?: boolean }
interface LessonDetail extends CurriculumLessonItem { description?: string; materials?: LessonMaterial[]; quiz?: LessonQuiz | null }
type ModuleForm = { id?: string; title: string } | null;
type ContentDialog = { type: 'material' | 'quiz'; lessonId: string } | null;

const getErrorMessage = (error: unknown, fallback: string) => error && typeof error === 'object' && 'message' in error ? String(error.message) : fallback;
const materialLabel: Record<LessonMaterial['type'], string> = { youtube: 'YouTube', PDF: 'PDF', audio: 'Audio', drive: 'Google Drive', DOCX: 'DOCX', link: 'Tautan' };

function MeetingCard({ lesson, onEdit, onMaterial, onQuiz, onDelete }: { lesson: CurriculumLessonItem; onEdit: () => void; onMaterial: () => void; onQuiz: () => void; onDelete: () => void }) {
  const [expanded, setExpanded] = useState(false);
  const [previewIndex, setPreviewIndex] = useState(0);
  const detailQuery = useOne<LessonDetail>({ resource: 'lessons', id: lesson.id, queryOptions: { enabled: expanded } });
  const detail = detailQuery.result;
  const materials = detail?.materials || [];
  const activeMaterial = materials[previewIndex] || materials[0];
  const iconFor = (type: LessonMaterial['type']) => type === 'youtube' ? Video : type === 'audio' ? FileAudio : type === 'link' || type === 'drive' ? Link2 : FileText;

  return <article className="overflow-hidden rounded-xl border border-slate-700 bg-slate-900">
    <div className="flex min-w-0 flex-col gap-3 p-4 sm:flex-row sm:items-center">
      <button type="button" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded} className="flex min-w-0 flex-1 items-start gap-3 rounded-lg text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400">
        <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-800 text-xs font-bold text-slate-300">{lesson.sequence}</span>
        <span className="min-w-0 flex-1"><span className="block break-words text-sm font-bold text-white">{lesson.title}</span><span className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Files className="h-3.5 w-3.5" /> {lesson.materialCount || 0} materi</span><span className="inline-flex items-center gap-1"><FileQuestion className="h-3.5 w-3.5" /> {lesson.hasQuiz ? 'Ada kuis' : 'Tanpa kuis'}</span><span className={lesson.status === 'published' ? 'text-emerald-400' : 'text-amber-400'}>{lesson.status === 'published' ? 'Terbit' : 'Draft'}</span></span></span>
        <ChevronDown className={`mt-2 h-4 w-4 shrink-0 text-slate-500 transition-transform motion-reduce:transition-none ${expanded ? 'rotate-180' : ''}`} />
      </button>
      <div className="flex shrink-0 items-center gap-1 border-t border-slate-800 pt-3 sm:border-0 sm:pt-0"><button type="button" onClick={onEdit} className="inline-flex min-h-10 items-center gap-2 rounded-lg px-3 text-xs font-bold text-slate-300 hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400"><Edit3 className="h-3.5 w-3.5" /> Edit</button><button type="button" onClick={onDelete} aria-label={`Hapus ${lesson.title}`} className="flex h-10 w-10 items-center justify-center rounded-lg text-rose-400 hover:bg-rose-950/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400"><Trash2 className="h-4 w-4" /></button></div>
    </div>
    {expanded && <div className="border-t border-slate-800 bg-slate-950/70 p-4 sm:p-5">
      {detailQuery.query.isLoading ? <div className="h-36 animate-pulse rounded-xl bg-slate-900 motion-reduce:animate-none" /> : <div className="grid gap-4 lg:grid-cols-[15rem_minmax(0,1fr)]">
        <div><div className="mb-3 flex items-center justify-between"><h4 className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">Daftar materi</h4><span className="text-xs text-slate-600">{materials.length} sumber</span></div><div className="space-y-2">{materials.map((material, index) => { const Icon = iconFor(material.type); return <button type="button" key={`${material.type}-${material.url}`} onClick={() => setPreviewIndex(index)} className={`flex min-h-11 w-full items-center gap-3 rounded-lg border px-3 text-left text-xs transition-colors ${index === previewIndex ? 'border-emerald-700 bg-emerald-950/40 text-emerald-200' : 'border-slate-800 bg-slate-900 text-slate-300 hover:border-slate-700'}`}><Icon className="h-4 w-4 shrink-0" /><span className="min-w-0 flex-1 truncate">{material.filename || materialLabel[material.type]}</span></button>; })}{materials.length === 0 && <p className="rounded-lg border border-dashed border-slate-700 px-4 py-6 text-center text-xs text-slate-500">Belum ada materi.</p>}</div></div>
        <div><h4 className="mb-3 text-xs font-bold uppercase tracking-[0.12em] text-slate-400">Pratinjau</h4>{activeMaterial ? <MaterialViewer material={activeMaterial} tone="admin" compact /> : <div className="flex min-h-36 items-center justify-center rounded-xl border border-dashed border-slate-700 text-center text-xs text-slate-500">Tambahkan materi untuk melihat pratinjau di sini.</div>}</div>
      </div>}
    </div>}
    <div className="grid border-t border-slate-800 sm:grid-cols-2"><button type="button" onClick={onMaterial} className="group flex min-h-16 items-center gap-3 px-4 text-left hover:bg-emerald-950/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-emerald-400"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-emerald-950 text-emerald-300"><Plus className="h-4 w-4" /></span><span><span className="block text-sm font-bold text-emerald-200">Tambah materi</span><span className="mt-0.5 block text-xs text-slate-500">Video, PDF, audio, atau tautan</span></span></button><button type="button" onClick={onQuiz} className="group flex min-h-16 items-center gap-3 border-t border-slate-800 px-4 text-left hover:bg-amber-950/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-amber-400 sm:border-l sm:border-t-0"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-amber-950/60 text-amber-300"><FileQuestion className="h-4 w-4" /></span><span><span className="block text-sm font-bold text-amber-200">{lesson.hasQuiz ? 'Kelola kuis' : 'Tambah kuis'}</span><span className="mt-0.5 block text-xs text-slate-500">Passing grade dan bank soal</span></span></button></div>
  </article>;
}

export function AdminCurriculumPage() {
  const { id: programId } = useParams<{ id: string }>();
  const [lessonEditor, setLessonEditor] = useState<{ lessonId: string | null; chapterId?: string } | null>(null);
  const [contentDialog, setContentDialog] = useState<ContentDialog>(null);
  const [moduleForm, setModuleForm] = useState<ModuleForm>(null);
  const [feedback, setFeedback] = useState<{ type: 'error' | 'success'; message: string } | null>(null);
  const chaptersQuery = useList<ChapterItem>({ resource: 'chapters', filters: [{ field: 'programId', operator: 'eq', value: programId }], sorters: [{ field: 'sequence', order: 'asc' }], pagination: { mode: 'off' } });
  const lessonsQuery = useList<CurriculumLessonItem>({ resource: 'lessons', filters: [{ field: 'programId', operator: 'eq', value: programId }], sorters: [{ field: 'sequence', order: 'asc' }], pagination: { mode: 'off' } });
  const { mutate: createChapter, mutation: createChapterMutation } = useCreate(); const { mutate: updateChapter, mutation: updateChapterMutation } = useUpdate(); const { mutate: deleteChapter } = useDelete(); const { mutate: deleteLesson } = useDelete();
  const chapters = chaptersQuery.result.data; const lessons = lessonsQuery.result.data; const ungroupedLessons = useMemo(() => lessons.filter((lesson) => !lesson.chapterId), [lessons]);
  const isLoading = chaptersQuery.query.isLoading || lessonsQuery.query.isLoading; const isSavingModule = Boolean(createChapterMutation.isPending || updateChapterMutation.isPending);
  const refresh = () => void Promise.all([chaptersQuery.query.refetch(), lessonsQuery.query.refetch()]);
  const savedContent = () => { setFeedback({ type: 'success', message: 'Konten pertemuan berhasil diperbarui.' }); refresh(); };
  const saveModule = () => { if (!moduleForm?.title.trim()) return; setFeedback(null); const options = { onSuccess: () => { setModuleForm(null); setFeedback({ type: 'success' as const, message: 'Modul berhasil disimpan.' }); refresh(); }, onError: (error: unknown) => setFeedback({ type: 'error' as const, message: getErrorMessage(error, 'Modul belum dapat disimpan.') }) }; if (moduleForm.id) updateChapter({ resource: 'chapters', id: moduleForm.id, values: { title: moduleForm.title.trim() } }, options); else createChapter({ resource: 'chapters', values: { programId, title: moduleForm.title.trim(), sequence: chapters.length + 1 } }, options); };
  const removeModule = (chapter: ChapterItem) => { const count = lessons.filter((lesson) => lesson.chapterId === chapter.id).length; if (count) return setFeedback({ type: 'error', message: `Modul “${chapter.title}” masih memiliki ${count} pertemuan.` }); if (!window.confirm(`Hapus modul “${chapter.title}”?`)) return; deleteChapter({ resource: 'chapters', id: chapter.id }, { onSuccess: refresh, onError: (error) => setFeedback({ type: 'error', message: getErrorMessage(error, 'Modul belum dapat dihapus.') }) }); };
  const removeLesson = (lesson: CurriculumLessonItem) => { if (!window.confirm(`Hapus pertemuan “${lesson.title}” beserta materi dan kuisnya?`)) return; deleteLesson({ resource: 'lessons', id: lesson.id }, { onSuccess: () => { setFeedback({ type: 'success', message: 'Pertemuan berhasil dihapus.' }); refresh(); }, onError: (error) => setFeedback({ type: 'error', message: getErrorMessage(error, 'Pertemuan belum dapat dihapus.') }) }); };
  const lessonList = (items: CurriculumLessonItem[], chapterId?: string) => <div className="space-y-3">{items.map((lesson) => <MeetingCard key={lesson.id} lesson={lesson} onEdit={() => setLessonEditor({ lessonId: lesson.id, chapterId })} onMaterial={() => setContentDialog({ type: 'material', lessonId: lesson.id })} onQuiz={() => setContentDialog({ type: 'quiz', lessonId: lesson.id })} onDelete={() => removeLesson(lesson)} />)}{items.length === 0 && <div className="rounded-xl border border-dashed border-slate-700 px-5 py-8 text-center"><p className="text-sm font-semibold text-slate-300">Belum ada pertemuan</p><button type="button" onClick={() => setLessonEditor({ lessonId: null, chapterId })} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-lg px-3 text-xs font-bold text-emerald-300 hover:bg-emerald-950/50"><Plus className="h-3.5 w-3.5" /> Tambah pertemuan</button></div>}</div>;
  if (isLoading) return <div className="h-80 animate-pulse rounded-xl bg-slate-800" />;

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 rounded-xl border border-slate-700 bg-slate-950 p-5 sm:flex-row sm:items-end sm:justify-between sm:p-6"><div><h2 className="flex items-center gap-2 text-xl font-bold text-white"><BookOpenCheck className="h-5 w-5 text-emerald-400" /> Pertemuan, materi, dan kuis</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-400">Buka kartu pertemuan untuk melihat pratinjau. Tambahkan materi dan kuis langsung dari tombol terpisah di setiap kartu.</p></div><div className="flex flex-col gap-2 sm:flex-row"><button type="button" onClick={() => setModuleForm({ title: '' })} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-slate-700 px-4 text-sm font-bold text-slate-200 hover:bg-slate-800"><Plus className="h-4 w-4" /> Tambah modul</button><button type="button" onClick={() => setLessonEditor({ lessonId: null })} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-bold text-white hover:bg-emerald-500"><Plus className="h-4 w-4" /> Tambah pertemuan</button></div></section>
    {feedback && <div role={feedback.type === 'error' ? 'alert' : 'status'} className={`flex items-start justify-between gap-3 rounded-lg border px-4 py-3 text-sm ${feedback.type === 'error' ? 'border-rose-800 bg-rose-950/40 text-rose-200' : 'border-emerald-800 bg-emerald-950/40 text-emerald-200'}`}><span>{feedback.message}</span><button type="button" onClick={() => setFeedback(null)} aria-label="Tutup notifikasi" className="flex h-8 w-8 items-center justify-center rounded-md hover:bg-white/10"><X className="h-4 w-4" /></button></div>}
    {ungroupedLessons.length > 0 && <section className="rounded-xl border border-slate-700 bg-slate-950 p-4 sm:p-5"><div className="mb-4"><h3 className="text-base font-bold text-white">Pertemuan langsung</h3><p className="mt-1 text-xs text-slate-500">Pertemuan yang tidak dikelompokkan dalam modul.</p></div>{lessonList(ungroupedLessons)}</section>}
    <div className="space-y-4">{chapters.map((chapter, index) => { const chapterLessons = lessons.filter((lesson) => lesson.chapterId === chapter.id); return <section key={chapter.id} className="overflow-hidden rounded-xl border border-slate-700 bg-slate-950"><header className="flex flex-col gap-3 border-b border-slate-800 bg-slate-900/60 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Modul {index + 1}</p><h3 className="mt-1 break-words text-base font-bold text-white">{chapter.title}</h3><p className="mt-1 text-xs text-slate-500">{chapterLessons.length} pertemuan · {chapterLessons.reduce((sum, lesson) => sum + (lesson.materialCount || 0), 0)} materi</p></div><div className="flex gap-1"><button type="button" onClick={() => setModuleForm({ id: chapter.id, title: chapter.title })} aria-label={`Edit modul ${chapter.title}`} className="flex h-10 w-10 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-800 hover:text-white"><Edit3 className="h-4 w-4" /></button><button type="button" onClick={() => removeModule(chapter)} aria-label={`Hapus modul ${chapter.title}`} className="flex h-10 w-10 items-center justify-center rounded-lg text-rose-400 hover:bg-rose-950/50"><Trash2 className="h-4 w-4" /></button></div></header><div className="p-4">{lessonList(chapterLessons, chapter.id)}<button type="button" onClick={() => setLessonEditor({ lessonId: null, chapterId: chapter.id })} className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-dashed border-slate-700 text-sm font-bold text-emerald-300 hover:border-emerald-700 hover:bg-emerald-950/30"><Plus className="h-4 w-4" /> Tambah pertemuan ke modul</button></div></section>; })}</div>
    {chapters.length === 0 && ungroupedLessons.length === 0 && <div className="rounded-xl border border-dashed border-slate-700 bg-slate-950 px-5 py-12 text-center"><h3 className="text-base font-bold text-white">Program belum memiliki pertemuan</h3><p className="mx-auto mt-2 max-w-lg text-sm text-slate-500">Buat pertemuan terlebih dahulu, lalu tambahkan materi dan kuis dari kartunya.</p><button type="button" onClick={() => setLessonEditor({ lessonId: null })} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-bold text-white hover:bg-emerald-500"><Plus className="h-4 w-4" /> Buat pertemuan pertama</button></div>}
    {moduleForm && <div className="fixed inset-0 z-[110] flex items-end justify-center bg-slate-950/85 sm:items-center sm:p-4"><div role="dialog" aria-modal="true" aria-labelledby="module-form-title" className="w-full rounded-t-2xl border border-slate-700 bg-slate-950 p-5 sm:max-w-md sm:rounded-2xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 id="module-form-title" className="text-lg font-bold text-white">{moduleForm.id ? 'Edit modul' : 'Tambah modul'}</h2><p className="mt-1 text-xs text-slate-500">Modul bersifat opsional.</p></div><button type="button" onClick={() => setModuleForm(null)} disabled={isSavingModule} aria-label="Tutup formulir modul" className="flex h-10 w-10 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-800"><X className="h-4 w-4" /></button></div><label className="mt-5 block space-y-2"><span className="text-sm font-semibold text-slate-300">Nama modul *</span><input autoFocus required value={moduleForm.title} onChange={(event) => setModuleForm({ ...moduleForm, title: event.target.value })} onKeyDown={(event) => { if (event.key === 'Enter') saveModule(); }} className="min-h-11 w-full rounded-lg border border-slate-700 bg-slate-900 px-3.5 text-sm text-white outline-none focus:border-emerald-500" /></label><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => setModuleForm(null)} className="min-h-11 rounded-lg px-4 text-sm font-semibold text-slate-300 hover:bg-slate-800">Batal</button><button type="button" onClick={saveModule} disabled={isSavingModule || !moduleForm.title.trim()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-bold text-white disabled:opacity-50">{isSavingModule && <LoaderCircle className="h-4 w-4 animate-spin" />} Simpan modul</button></div></div></div>}
    {lessonEditor && <AdminLessonForm lessonId={lessonEditor.lessonId} programId={programId} chapterId={lessonEditor.chapterId} onClose={() => { setLessonEditor(null); refresh(); }} />}
    {contentDialog?.type === 'material' && <AdminMaterialDialog lessonId={contentDialog.lessonId} onClose={() => setContentDialog(null)} onSuccess={savedContent} />}
    {contentDialog?.type === 'quiz' && <AdminQuizDialog lessonId={contentDialog.lessonId} onClose={() => setContentDialog(null)} onSuccess={savedContent} />}
  </div>;
}
